# Base de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/movies_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# TMDB
tmdb.api.key=bd1e9bb21757568ec47023efed3a3612
tmdb.api.base-url=https://api.themoviedb.org/3

# Porta
server.port=8085